name: Название вашего CI пайплайна для проекта

on:
  push:
    branches:
      При пуши на ветку, которую вы указали вот тут, будет запускаться пайплайн

env:
  CR_REGISTRY: [[README CR_REGISTRY Шаг 3]]
  CR_REPOSITORY: [[README CR_REPOSITORY Шаг 4]]
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: Yandex Cloud CR "Login" Action for GitHub Actions
        uses: yc-actions/yc-cr-login@v0.1-alpha

        with:
          yc-sa-json-credentials: ${{ [[README Получение JSON авторизации для сервисного аккаунта]] }}
      - name: Build, tag, and push image to Yandex Cloud Container Registry
        run: |
          docker build --target [[README_Dockerfile_target]] -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:[[README_Dockerfile_image_name]]-$IMAGE_TAG -f [[README_Dockerfile]] .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:[[README_Dockerfile_image_name]]-$IMAGE_TAG
          



  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install and init Yandex Cloud CLI
      env:
        YC_SERVICE_ACCOUNT_KEY: ${{ [[README Получение JSON авторизации для сервисного аккаунта(выбираем нужный ключ)]] }}
      run: |
        curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
        shopt -s expand_aliases
        alias yc="/home/runner/yandex-cloud/bin/yc"
        yc config profile create deployer
        echo "$YC_SERVICE_ACCOUNT_KEY" > ./sa-key.json
        yc config set service-account-key ./sa-key.json


    - name: Deploy to Yandex Cloud Serverless Containers
      run: |
        shopt -s expand_aliases
        alias yc="/home/runner/yandex-cloud/bin/yc"
        yc serverless container revision deploy \
          --container-id $YC_CONTAINER_ID \
          --image cr.yandex/$CR_REGISTRY/$CR_PROD_REPOSITORY:[[README_Dockerfile_image_name]]-$IMAGE_TAG \
          --cores 1 \
          --memory 1GB \
          --concurrency 5 \
          --min-instances 0 \
          --zone-instances-limit 3 \
          --zone-requests-limit 15 \
          --execution-timeout 90s \
          --log-group-id [[README ID лог группы]] \
          --network-id [[README ID сети]] \
          --service-account-id ${{ [[README Получение ID сервисного аккаунта]] }}
          --secret environment-variable=[[README Секреты для деплоя, id и ключ (пример ниже)]] \
          --secret environment-variable=BIG_SECRET,id=qwe123rty4567890,key=BIG_SECRET


