name: Название вашего CI пайплайна для проекта

on:
  push:
    branches:
      При пуши на ветку, которую вы указали вот тут, будет запускаться пайплайн

env:
  CR_REGISTRY: README CR_REGISTRY
  CR_REPOSITORY: README CR_REPOSITORY
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: Yandex Cloud CR "Login" Action for GitHub Actions
        uses: yc-actions/yc-cr-login@v0.1-alpha

        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
      - name: Build, tag, and push image to Yandex Cloud Container Registry
        run: |
          docker build --target site -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:site-$IMAGE_TAG -f test.Dockerfile .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:site-$IMAGE_TAG
          
          docker build --target daemon -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:daemon-$IMAGE_TAG -f test.Dockerfile .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:daemon-$IMAGE_TAG

      - name: Send Telegram notification
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          # message_thread_id: ${{ secrets.TELEGRAM_THREAD_ID }}  # ID треда
          message: |
            🔔сборка ${{ job.status }}
            ‍👨🏿‍💻автор ${{ github.actor }}
            репозиторий: ${{ github.repository }}
            ветка: ${{ github.ref }}
            коммит: ${{ github.sha }}


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install and init Yandex Cloud CLI
      env:
        YC_SERVICE_ACCOUNT_KEY: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
      run: |
        curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
        shopt -s expand_aliases
        alias yc="/home/runner/yandex-cloud/bin/yc"
        yc config profile create deployer
        echo "$YC_SERVICE_ACCOUNT_KEY" > ./sa-key.json
        yc config set service-account-key ./sa-key.json

    - name: Get kubeconfig
      run: |
        shopt -s expand_aliases
        alias yc="/home/runner/yandex-cloud/bin/yc"
        yc managed-kubernetes cluster get-credentials --id ${{ secrets.YC_CLUSTER_ID }} --external
        echo "K8S_CONTEXT_NAME=$(yc managed-kubernetes cluster get cat90fh1a1m05rh0118j --format=json | jq '.name')" >> $GITHUB_ENV

    - name: Deploy Testing Site to Kubernetes
      run: |
        kubectl config use-context yc-${{ env.K8S_CONTEXT_NAME }}
        sed -i "s,VERSION,cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:site-$IMAGE_TAG," testing.yaml
        kubectl apply -f testing.yaml -n testing
        

    - name: Deploy Testing Daemon to Kubernetes
      run: |
        kubectl config use-context yc-${{ env.K8S_CONTEXT_NAME }}
        sed -i "s,VERSION,cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:daemon-$IMAGE_TAG," daemon.yaml
        kubectl apply -f daemon.yaml -n testing
        

        sed -i "s,VERSION,cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:daemon-$IMAGE_TAG," kubernetes_cron/cronjob.yaml
        kubectl apply -f kubernetes_cron/cronjob.yaml -n testing
        
        
        sed -i "s,VERSION,cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:daemon-$IMAGE_TAG," kubernetes_cron/1hour/test-orders-statistics-1h.yaml
        kubectl apply -f kubernetes_cron/1hour/test-orders-statistics-1h.yaml -n testing

        sed -i "s,VERSION,cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:daemon-$IMAGE_TAG," kubernetes_cron/24hour/test-orders-statistics-24h.yaml
        kubectl apply -f kubernetes_cron/24hour/test-orders-statistics-24h.yaml -n testing
#        kubectl apply -f kubernetes_cron/delete_failed_pods.yaml -n testing
    - name: Send Telegram notification
      if: always()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        # message_thread_id: ${{ secrets.TELEGRAM_THREAD_ID }}  # ID треда
        message: |
          🔔 деплой ${{ job.status }}
          👨🏿‍💻автор: ${{ github.actor }}
          репозиторий: ${{ github.repository }}
          ветка: ${{ github.ref }}
          коммит: ${{ github.sha }}
